#! /bin/bash

set -e

echo "------------------------------"
echo " 👀 Building icons ..."
echo "------------------------------"
npm run build:icons

echo "------------------------------"
echo " 📚 Building docs ..."
echo "------------------------------"
npm run build:customizations

echo "------------------------------"
echo " 🌈 Building styles ..."
echo "------------------------------"
npm run build:styles

echo "------------------------------"
echo " 📦 Bundling ..."
echo "------------------------------"
esbuild dist/index.css --outfile=dist/index.min.css --bundle --minify

echo ""
echo "> ✅ Done!"
